---
version: "3"

includes:
  rustpython:
    taskfile: rustpython/Taskfile.yaml
    optional: true
  pyoxidizer:
    taskfile: pyoxidizer/Taskfile.yaml
    optional: true

tasks:

  list:
    cmds:
      - cmd: 'task --list'
