---
version: '3.7'

# Project name
name: oxpython3

services:

  build-rustpython:
    image: ${BUILD_IMAGE}
    environment:
      - TARGET=${TARGET}
      - FEATURES=${FEATURES}
      - WORKDIR=/rustpython
    entrypoint: /app/entrypoint-nix.sh
    volumes:
      # Mount the repo in Docker
      - ./${RUSTPYTHON_REPO}:/rustpython
      - .:/app
