---
version: '3.7'

# Project name
name: ${APP_NAME}

services:

  build-stage:
    image: ${APP_NAME}-${IMAGE_NAME}
    container_name: ${APP_NAME}-${CONTAINER_NAME}
    environment:
      - TARGET=${TARGET}
      - PYOXIDIZER_VERSION=${PYOXIDIZER_VERSION}
      - WORKDIR=/app
    stdin_open: true    # docker run -i
    tty: true           # docker run -t
    # entrypoint: /app/entrypoint-nix.sh
    # entrypoint: /bin/bash
    volumes:
      - .:/app
